### ISSUE TITLE
Consider providing Stockfish builds for armv7l (Raspberry Pi)

### ISSUE THREAD

**Issue by Grishkaone** [niklasf/fishnet#104]
Hi !

The fishnet installation on a RPI seems to fail. Is this a compilation issue ?

**Comment by niklasf** [comment]
Can you please share the error message / log?

**Comment by Grishkaone** [comment]
Of course, sorry for forgetting !

```
sudo pip install --upgrade --user fishnet
Collecting fishnet
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```

Honestly I don't understand the error. Fishnet is running fine on my Mac, no trouble for the installation. I was hopping to add one or more RPi to help.

**Comment by niklasf** [comment]
Mhh ... wierd. This appears to be an issue with pip, before fishnet even runs. This thread on Stackoverflow suggests a network issue or outdated setuptools: https://stackoverflow.com/a/55273994/722291

**Comment by Grishkaone** [comment]
Thanks for the tips.
I tried a few things, but always got the same error. Finally, I reinstall a fresh version au Raspbian and it's working. I just need to solve the "The script chardetect is installed in '/root/.local/bin' which is not on PATH." think now. Hope to get it work tonight :)

**Comment by Grishkaone** [comment]
Hello, me again !

The initial Fishnet configuration is working well, but after that :

```
WARNING: Unexpected cpuid output: Traceback (most recent call last):
WARNING: Unexpected cpuid output:   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
WARNING: Unexpected cpuid output:     "__main__", fname, loader, pkg_name)
WARNING: Unexpected cpuid output:   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
WARNING: Unexpected cpuid output:     exec code in run_globals
WARNING: Unexpected cpuid output:   File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1941, in <module>
WARNING: Unexpected cpuid output:     sys.exit(main(sys.argv))
WARNING: Unexpected cpuid output:   File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1925, in main
WARNING: Unexpected cpuid output:     sys.exit(commands[args.command](args))
WARNING: Unexpected cpuid output:   File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1861, in cmd_cpuid
WARNING: Unexpected cpuid output:     with make_cpuid() as cpuid:
WARNING: Unexpected cpuid output:   File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
WARNING: Unexpected cpuid output:     return self.gen.next()
WARNING: Unexpected cpuid output:   File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1740, in make_cpuid
WARNING: Unexpected cpuid output:     raise OSError("Got no CPUID opcodes for %s" % platform.machine())
WARNING: Unexpected cpuid output: OSError: Got no CPUID opcodes for armv7l
DEBUG: Package: "", name: __main__, loader: <pkgutil.ImpLoader instance at 0x76a39418>
DEBUG: Pip: pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
DEBUG: cpuid >> Traceback (most recent call last):
DEBUG: cpuid >>   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
DEBUG: cpuid >>     "__main__", fname, loader, pkg_name)
DEBUG: cpuid >>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
DEBUG: cpuid >>     exec code in run_globals
DEBUG: cpuid >>   File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1941, in <module>
DEBUG: cpuid >>     sys.exit(main(sys.argv))
DEBUG: cpuid >>   File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1925, in main
DEBUG: cpuid >>     sys.exit(commands[args.command](args))
DEBUG: cpuid >>   File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1861, in cmd_cpuid
DEBUG: cpuid >>     with make_cpuid() as cpuid:
DEBUG: cpuid >>   File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
DEBUG: cpuid >>     return self.gen.next()
DEBUG: cpuid >>   File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1740, in make_cpuid
DEBUG: cpuid >>     raise OSError("Got no CPUID opcodes for %s" % platform.machine())
DEBUG: cpuid >> OSError: Got no CPUID opcodes for armv7l
ERROR: cpuid exited with status code 1
Engine target path: /home/pi/stockfish-armv7l
Looking up stockfish-armv7l ...
Latest release is tagged fishnet-180120
ERROR: Configuration error
Traceback (most recent call last):
  File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1925, in main
    sys.exit(commands[args.command](args))
  File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1505, in cmd_run
    stockfish_command = get_stockfish_command(conf)
  File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1443, in get_stockfish_command
    filename = update_stockfish(conf, filename)
  File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1048, in update_stockfish
    return download_github_release(conf, STOCKFISH_RELEASES, filename)
  File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1018, in download_github_release
    raise ConfigError("No precompiled %s for your platform" % filename)
ConfigError: No precompiled stockfish-armv7l for your platform
```

The message is the same on a RPi 3A+ and a RPI Zero W (this one for testing).

**Comment by niklasf** [comment]
Ah, there are currently no binaries available for the architecture :(

I'll keep this issue as a reminder, but it's low priority.

**Comment by mayweed** [comment]
Hello
I got exactly the same problem except that i already have stockfish compiled for armv7 on my platform. And an up-to-date one. Is there any way /option to prevent the force update and go with the preinstalled one? Would be great...
Thx

**Comment by niklasf** [comment]
```
$ python3 -c "import sys,os,platform;print(os.name);print(platform.machine());print(sys.platform)"
posix
armv7l
linux
```

**Comment by niklasf** [comment]
2 x Cavium ThunderX CN8890:

```$ python3 -c "import sys,os,platform;print(os.name);print(platform.machine());print(sys.platform)"
posix
aarch64
linux
```

**Comment by niklasf** [comment]
Version 2.x will draw the line at 64 bits. So aarch64 will be supported, but not armv7.

**Comment by Grishkaone** [comment]
> 
> 
> Version 2.x will draw the line at 64 bits. So aarch64 will be supported, but not armv7.

Ok ! What about armv8 on something like the Raspberry Pi 4 ?

**Comment by niklasf** [comment]
That should work. If you have an opportunity to test it, please [try](https://github.com/niklasf/fishnet/tree/2.x#installation) the aarch64 version from the latest pre-release: https://github.com/niklasf/fishnet/releases
