### ISSUE TITLE
seen this exception on 2 machines

### ISSUE THREAD

**Issue by ornicar** [niklasf/fishnet#61]
one KS-24 and a linux laptop on ubuntu 16.04:

```
May 07 16:02:58 flynn python3[3444]: ><> 1: Started engine process, pid: 25857, threads: 4, identification: Stockfish 160416 64 POPCNT
May 07 16:03:04 flynn python3[3444]: ><> 3: http://en.lichess.org/HxEmky9K took 103.0s (2.06s per position)
May 07 16:03:24 flynn python3[3444]: ><> 2: http://en.lichess.org/FEyNLNLA took 107.9s (1.96s per position)
May 07 16:03:28 flynn python3[3444]: [fishnet v1.5.1] Analyzed 1363997 positions, crunched 3974297 million nodes
May 07 16:03:43 flynn python3[3444]: ><> 4: http://en.lichess.org/glIQrM9z took 89.1s (1.94s per position)
May 07 16:04:28 flynn python3[3444]: [fishnet v1.5.1] Analyzed 1364097 positions, crunched 3974595 million nodes
May 07 16:05:02 flynn python3[3444]: ><> 1: ERROR: Backing off 0.6s after exception in worker
May 07 16:05:02 flynn python3[3444]: Traceback (most recent call last):
May 07 16:05:02 flynn python3[3444]: File "/usr/local/lib/python3.4/dist-packages/fishnet.py", line 571, in run_inner
May 07 16:05:02 flynn python3[3444]: path, request = self.work()
May 07 16:05:02 flynn python3[3444]: File "/usr/local/lib/python3.4/dist-packages/fishnet.py", line 667, in work
May 07 16:05:02 flynn python3[3444]: result["analysis"] = self.analysis(self.job)
May 07 16:05:02 flynn python3[3444]: File "/usr/local/lib/python3.4/dist-packages/fishnet.py", line 722, in analysis
May 07 16:05:02 flynn python3[3444]: if "mate" not in part["score"] and "time" in part and part["time"] < 100:
May 07 16:05:02 flynn python3[3444]: KeyError: 'score'
May 07 16:05:04 flynn python3[3444]: ><> 4: http://en.lichess.org/7anvjhz1 took 77.1s (1.61s per position)
May 07 16:05:06 flynn python3[3444]: ><> 1: Started engine process, pid: 25867, threads: 4, identification: Stockfish 160416 64 POPCNT
May 07 16:05:20 flynn python3[3444]: ><> 2: http://en.lichess.org/FAFhmqp9 took 115.5s (1.52s per position)
```

**Comment by niklasf** [comment]
I am assuming Stockfish will report a score at least once. I'll double check that.

**Comment by niklasf** [comment]
Reproduced with verbose log:
```
><> 1: Analysing http://en.lichess.org/VtO83Chg#37
><> 1: ENGINE: 18706 << position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 moves e2e4 e7e6 b1c3 d7d6 g1f3 a7a6 d2d3 b8c6 f3g5 h7h6 g5h3 e6e5 d3d4 c6d4 c3a4 c8h3 g2h3 d8d7 a4c3 c7c5 c3d5 g8e7 d5e7 f8e7 c2c3 d4c6 d1g4 e8g8 g4d7 a8b8 d7g4 c6a5 b2b3 f7f6 f1c4 a5c4 b3c4
><> 1: ENGINE: 18706 << isready
><> 1: ENGINE: 18706 >> readyok
><> 1: ENGINE: 18706 << go movetime 4000 nodes 3000000
><> 1: ENGINE: 18706 >> info depth 1 seldepth 1 multipv 1 score cp -905 nodes 38 nps 19000 tbhits 0 time 2 pv g8h8
><> 1: ENGINE: 18706 >> info depth 2 seldepth 2 multipv 1 score cp -909 nodes 88 nps 44000 tbhits 0 time 2 pv g8h8 c1e3
><> 1: ENGINE: 18706 >> info depth 3 seldepth 3 multipv 1 score cp -934 nodes 269 nps 89666 tbhits 0 time 3 pv f6f5 e4f5 e7f6
><> 1: ENGINE: 18706 >> info depth 4 seldepth 4 multipv 1 score cp -973 nodes 534 nps 133500 tbhits 0 time 4 pv f6f5 g4g6 f8f7 e4f5
><> 1: ENGINE: 18706 >> info depth 5 seldepth 6 multipv 1 score cp -955 nodes 1431 nps 286200 tbhits 0 time 5 pv f6f5 g4g6 f8f7 e4f5 b7b5
><> 1: ENGINE: 18706 >> info depth 6 seldepth 7 multipv 1 score cp -979 nodes 3532 nps 441500 tbhits 0 time 8 pv g7g5 h1g1 b7b5 c1e3 b5c4 g4e6 f8f7
><> 1: ENGINE: 18706 >> info depth 7 seldepth 8 multipv 1 score cp -979 nodes 6333 nps 575727 tbhits 0 time 11 pv g7g5 a1b1 b7b5 c4b5 a6b5 g4e6 f8f7 e1e2
><> 1: ENGINE: 18706 >> info depth 8 seldepth 9 multipv 1 score cp -992 nodes 14802 nps 643565 tbhits 0 time 23 pv g7g5 g4d7 f8e8 a1b1 b7b5 c4b5 a6b5 b1b5
><> 1: ENGINE: 18706 >> info depth 9 seldepth 13 multipv 1 score cp -1001 nodes 22733 nps 688878 tbhits 0 time 33 pv g7g5 g4d7 g8f7 h1g1 f8d8 d7g4 b7b5 c4b5 a6b5
><> 1: ENGINE: 18706 >> info depth 10 seldepth 15 multipv 1 score cp -1014 nodes 61859 nps 883700 tbhits 0 time 70 pv g7g5 a1b1 f8f7 e1e2 b7b6 c1e3 g8h8 h1g1 b6b5 h3h4 f7g7 c4b5
><> 1: ENGINE: 18706 >> info depth 11 seldepth 16 multipv 1 score cp -1031 nodes 132994 nps 923569 tbhits 0 time 144 pv g7g5 a1b1 b7b6 c1e3 b8b7 g4h5 g8g7 h1g1 b6b5 e1e2 b5b4 c3b4
><> 1: ENGINE: 18706 >> info depth 12 seldepth 16 multipv 1 score cp -1042 nodes 218654 nps 871131 tbhits 0 time 251 pv g7g5 a1b1 b7b6 c1e3 b8b7 g4h5 g8g7 h1g1 b6b5 h3h4 f8h8 e1e2 b5b4 c3b4 b7b4 h4g5 f6g5
><> 1: ENGINE: 18706 >> info depth 13 seldepth 20 multipv 1 score cp -1056 nodes 561069 nps 913793 tbhits 0 time 614 pv g7g5 a1b1 b7b6 c1e3 g8f7 e1e2 b6b5 c4b5 a6b5 h1g1 b8b7 h3h4 f7g7 g4h5
><> 1: ENGINE: 18706 >> info depth 14 seldepth 21 multipv 1 score cp -1060 nodes 698587 nps 891054 tbhits 0 time 784 pv g7g5 a1b1 b7b6 c1e3 g8f7 e1e2 b6b5 c4b5 a6b5 h1g1 b8a8 b1b5 a8a2 e2d3 a2a7 g4h5 f7g7 h3h4 f8h8 h4g5 f6g5
><> 1: ENGINE: 18706 >> info depth 15 seldepth 25 multipv 1 score cp -1079 nodes 1522469 nps 894517 hashfull 574 tbhits 0 time 1702 pv g8f7 h3h4 g7g5 h1g1 f8h8 a2a4 b7b6 h4h5 f7g8 g4e6 g8f8 a1b1 h8h7 e6d7 h7g7 d7c7
><> 1: ENGINE: 18706 >> info depth 16 seldepth 28 multipv 1 score cp -1090 nodes 2463462 nps 888374 hashfull 774 tbhits 0 time 2773 pv g8f7 h3h4 g7g5 h1g1 f8h8 a2a4 b7b6 h4h5 h8h7 g4d7 f7g8 a1b1 a6a5 d7c7 b8f8 c7b6 f6f5
><> 1: ENGINE: 18706 >> info depth 17 currmove f8f7 currmovenumber 3
><> 1: ENGINE: 18706 >> info depth 17 currmove b7b5 currmovenumber 4
><> 1: ENGINE: 18706 >> info depth 17 currmove a6a5 currmovenumber 5
><> 1: ENGINE: 18706 >> info depth 17 currmove b7b6 currmovenumber 6
><> 1: ENGINE: 18706 >> info depth 17 currmove g8h7 currmovenumber 7
><> 1: ENGINE: 18706 >> info depth 17 currmove g8h8 currmovenumber 8
><> 1: ENGINE: 18706 >> info depth 17 currmove b8d8 currmovenumber 9
><> 1: ENGINE: 18706 >> info depth 17 currmove f8d8 currmovenumber 10
><> 1: ENGINE: 18706 >> info depth 17 currmove d6d5 currmovenumber 11
><> 1: ENGINE: 18706 >> info depth 17 currmove f6f5 currmovenumber 12
><> 1: ENGINE: 18706 >> info depth 17 currmove b8e8 currmovenumber 13
><> 1: ENGINE: 18706 >> info depth 17 currmove f8e8 currmovenumber 14
><> 1: ENGINE: 18706 >> info depth 17 currmove h6h5 currmovenumber 15
><> 1: ENGINE: 18706 >> info depth 17 currmove e7d8 currmovenumber 16
><> 1: ENGINE: 18706 >> info depth 17 currmove g7g6 currmovenumber 17
><> 1: ENGINE: 18706 >> info depth 17 currmove b8a8 currmovenumber 18
><> 1: ENGINE: 18706 >> info depth 17 currmove f8c8 currmovenumber 19
><> 1: ENGINE: 18706 >> info depth 17 currmove b8c8 currmovenumber 20
><> 1: ENGINE: 18706 >> info depth 17 seldepth 28 multipv 1 score cp -1097 upperbound nodes 2876430 nps 880449 hashfull 837 tbhits 0 time 3267 pv g8f7 h3h4
><> 1: ENGINE: 18706 >> info depth 17 currmove g8f7 currmovenumber 1
><> 1: ENGINE: 18706 >> info depth 17 currmove g7g5 currmovenumber 2
><> 1: ENGINE: 18706 >> info nodes 3002245 time 3429
><> 1: ENGINE: 18706 >> bestmove g8f7 ponder h3h4
><> 1: ENGINE: 18706 << isready
><> 1: ENGINE: 18706 >> readyok
><> 1: ERROR: Backing off 0.7s after exception in worker
Traceback (most recent call last):
  File "./fishnet.py", line 571, in run_inner
    path, request = self.work()
  File "./fishnet.py", line 667, in work
    result["analysis"] = self.analysis(self.job)
  File "./fishnet.py", line 722, in analysis
    if "mate" not in part["score"] and "time" in part and part["time"] < 100:
KeyError: 'score'
```
