### ISSUE TITLE
Build broken on osx

### ISSUE THREAD

**Issue by elmagow** [niklasf/fishnet#63]
Just puting it in a new thread:

```
### Updating Stockfish ...

Engine target path: /Library/Python/2.7/site-packages/fishnet/stockfish-osx-x86_64
Looking up stockfish-osx-x86_64 ...
Latest stockfish release is tagged fishnet-20160416
Found https://github.com/niklasf/Stockfish/releases/download/fishnet-20160416/stockfish-osx-x86_64
Downloading stockfish-osx-x86_64 ...
Downloading stockfish-osx-x86_64: 318776/318776 (100%)
chmod +x stockfish-osx-x86_64
WARNING: Unexpected engine output: dyld: lazy symbol binding failed: Symbol not found: __ZNSt18condition_variableC1Ev
WARNING: Unexpected engine output: Referenced from: /Library/Python/2.7/site-packages/fishnet/./stockfish-osx-x86_64
WARNING: Unexpected engine output: Expected in: /usr/lib/libstdc++.6.dylib
WARNING: Unexpected engine output: dyld: Symbol not found: __ZNSt18condition_variableC1Ev
WARNING: Unexpected engine output: Referenced from: /Library/Python/2.7/site-packages/fishnet/./stockfish-osx-x86_64
WARNING: Unexpected engine output: Expected in: /usr/lib/libstdc++.6.dylib
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/fishnet/fishnet.py", line 1759, in <module>
    sys.exit(main(sys.argv))
  File "/Library/Python/2.7/site-packages/fishnet/fishnet.py", line 1743, in main
    sys.exit(commands[args.command](args))
  File "/Library/Python/2.7/site-packages/fishnet/fishnet.py", line 1364, in cmd_run
    engine_command = get_engine_command(conf)
  File "/Library/Python/2.7/site-packages/fishnet/fishnet.py", line 1297, in get_engine_command
    return validate_engine_command(os.path.join(".", filename), conf)
  File "/Library/Python/2.7/site-packages/fishnet/fishnet.py", line 1140, in validate_engine_command
    _, options = uci(process)
  File "/Library/Python/2.7/site-packages/fishnet/fishnet.py", line 363, in uci
    command, arg = recv(p)
  File "/Library/Python/2.7/site-packages/fishnet/fishnet.py", line 344, in recv
    raise EOFError()
EOFError
```

**Comment by niklasf** [comment]
Hi. I have just made a new build of OSX Stockfish. It's probably not working, yet, but can you please try it again and provide the new output?

**Comment by elmagow** [comment]
I must miss something, but where do I get the api key?

It seems that stockfish is working:
`><> 1: Started engine process, pid: 64866, threads: 1, identification: Stockfish 130516 64
`

**Comment by niklasf** [comment]
Ah, sorry, I was assuming you were trying to run fishnet for a local development instance of lila.

For the moment lichess.org can only accept analysis from "trusted" machines. I am working on it: https://github.com/niklasf/fishnet/milestones

Thanks a lot for testing! This has been really helpful.
