### ISSUE TITLE
autoupdate doesn't find pip3

### ISSUE THREAD

**Issue by ornicar** [niklasf/fishnet#77]
Upgrading fishnet manually with ubuntu's pip3:

```
root@ns320545:~# pip3 install --upgrade fishnet
Downloading/unpacking fishnet from https://pypi.python.org/packages/39/e6/c58b1d434974188014ae09a027f3b95d9ef2ceb3ec1edaf2c55b2a6103a5/fishnet-1.14.2.tar.gz#md5=2b3478d484db5faf51453959d4b330
37
  Downloading fishnet-1.14.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/fishnet/setup.py) egg_info for package fishnet
    
Requirement already up-to-date: requests in /usr/local/lib/python3.4/dist-packages (from fishnet)
Installing collected packages: fishnet
  Found existing installation: fishnet 1.14.1
    Uninstalling fishnet:
      Successfully uninstalled fishnet
  Running setup.py install for fishnet
    
Successfully installed fishnet
Cleaning up...
```

Now running fishnet:

```
root@ns320545:~# nice -n 5 python3 -m fishnet --auto-update --no-conf --engine-dir=/home/fishnet --apikey=IQ0YmW3y --cores=4 --threads=1 --memory=128
.   _________         .    .
.  (..       \_    ,  |\  /|
.   \       O  \  /|  \ \/ /
.    \______    \/ |   \  /      _____ _     _     _   _      _
.       vvvv\    \ |   /  |     |  ___(_)___| |__ | \ | | ___| |_
.       \^^^^  ==   \_/   |     | |_  | / __| '_ \|  \| |/ _ \ __|
.        `\_   ===    \.  |     |  _| | \__ \ | | | |\  |  __/ |_
.        / /\_   \ /      |     |_|   |_|___/_| |_|_| \_|\___|\__| 1.14.2
.        |/   \_  \|      /
.               \________/      Distributed Stockfish analysis for lichess.org


### Updating ...

DEBUG: Package: "", name: __main__, loader: <_frozen_importlib.SourceFileLoader object at 0x7fef52b01b38>
ERROR: Configuration error
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/fishnet.py", line 1008, in update_self
    import pip
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 61, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python3/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name 'IncompleteRead'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/fishnet.py", line 1888, in main
    sys.exit(commands[args.command](args))
  File "/usr/local/lib/python3.4/dist-packages/fishnet.py", line 1470, in cmd_run
    update_self()
  File "/usr/local/lib/python3.4/dist-packages/fishnet.py", line 1010, in update_self
    raise ConfigError("Auto update enabled, but pip not installed")
ConfigError: Auto update enabled, but pip not installed
```

**Comment by niklasf** [comment]
due to a version conflict with `requests` auto update is hard to support on old pip versions: 79cdcdf0e4acd078992f78b932a0d9540d5c072a
