### ISSUE TITLE
Connection aborted ??

### ISSUE THREAD

**Issue by lazydroid** [niklasf/fishnet#90]
Since a few hours ago, I've got the following in the logs, after this, the stockfish gets restarted, outputs all these UCI init commands, and back to this:
```

Jun 27 17:44:53 [11614]: Traceback (most recent call last):
Jun 27 17:44:53 [11614]:   File "/usr/local/lib/python2.7/dist-packages/fishnet.py", line 657, in run_inner
Jun 27 17:44:53 [11614]:     timeout=HTTP_TIMEOUT)
Jun 27 17:44:53 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 107, in post
Jun 27 17:44:53 [11614]:     return request('post', url, data=data, json=json, **kwargs)
Jun 27 17:44:53 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 53, in request
Jun 27 17:44:53 [11614]:     return session.request(method=method, url=url, **kwargs)
Jun 27 17:44:53 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
Jun 27 17:44:53 [11614]:     resp = self.send(prep, **send_kwargs)
Jun 27 17:44:53 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
Jun 27 17:44:53 [11614]:     r = adapter.send(request, **kwargs)
Jun 27 17:44:53 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 426, in send
Jun 27 17:44:53 [11614]:     raise ConnectionError(err, request=request)
Jun 27 17:44:53 [11614]: ConnectionError: ('Connection aborted.', BadStatusLine("''",))
Jun 27 17:44:57 [11614]: ><> 1: ERROR: Backing off 7.2s after exception in worker
Jun 27 17:44:57 [11614]: Traceback (most recent call last):
Jun 27 17:44:57 [11614]:   File "/usr/local/lib/python2.7/dist-packages/fishnet.py", line 657, in run_inner
Jun 27 17:44:57 [11614]:     timeout=HTTP_TIMEOUT)
Jun 27 17:44:57 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 107, in post
Jun 27 17:44:57 [11614]:     return request('post', url, data=data, json=json, **kwargs)
Jun 27 17:44:57 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 53, in request
Jun 27 17:44:57 [11614]:     return session.request(method=method, url=url, **kwargs)
Jun 27 17:44:57 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
Jun 27 17:44:57 [11614]:     resp = self.send(prep, **send_kwargs)
Jun 27 17:44:57 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
Jun 27 17:44:57 [11614]:     r = adapter.send(request, **kwargs)
Jun 27 17:44:57 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 447, in send
Jun 27 17:44:57 [11614]:     raise SSLError(e, request=request)
Jun 27 17:44:57 [11614]: SSLError: EOF occurred in violation of protocol (_ssl.c:590)

```

**Comment by lazydroid** [comment]
Here's the beginning of the problem:

```
Jun 27 16:05:34 [11614]: [fishnet v1.15.9] Analyzed 788051 positions, crunched 3074562 million nodes
Jun 27 16:06:34 [11614]: [fishnet v1.15.9] Analyzed 788051 positions, crunched 3074562 million nodes
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: No job found. Backing off 4.0s
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: No job found. Backing off 6.5s
Jun 27 16:07:33 [11614]: ><> 2: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 2: DEBUG: No job found. Backing off 8.5s
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: No job found. Backing off 4.6s
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: No job found. Backing off 5.0s
Jun 27 16:07:33 [11614]: ><> 2: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 2: DEBUG: No job found. Backing off 13.1s
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: No job found. Backing off 9.9s
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: No job found. Backing off 6.2s
Jun 27 16:07:33 [11614]: ><> 2: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 2: DEBUG: No job found. Backing off 12.7s
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: No job found. Backing off 10.2s
Jun 27 16:07:33 [11614]: ><> 2: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 2: DEBUG: No job found. Backing off 14.9s
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: No job found. Backing off 8.0s
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: No job found. Backing off 7.7s
Jun 27 16:07:33 [11614]: ><> 2: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 2: DEBUG: No job found. Backing off 16.6s
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: No job found. Backing off 14.2s
Jun 27 16:07:33 [11614]: ><> 2: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 2: DEBUG: No job found. Backing off 16.3s
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: "POST /fishnet/acquire HTTP/1.1" 204 0
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: No job found. Backing off 10.2s
Jun 27 16:07:33 [11614]: ><> 1: DEBUG: "POST /fishnet/acquire HTTP/1.1" 502 1733
Jun 27 16:07:33 [11614]: ><> 1: ERROR: Server error: HTTP 502 Bad Gateway. Backing off 12.6s
Jun 27 16:07:33 [11614]: ><> 2: DEBUG: "POST /fishnet/acquire HTTP/1.1" 502 1733
Jun 27 16:07:33 [11614]: ><> 2: ERROR: Server error: HTTP 502 Bad Gateway. Backing off 18.9s
Jun 27 16:07:34 [11614]: [fishnet v1.15.9] Analyzed 788051 positions, crunched 3074562 million nodes
Jun 27 16:07:46 [11614]: ><> 1: ERROR: Backing off 10.7s after exception in worker
Jun 27 16:07:46 [11614]: Traceback (most recent call last):
Jun 27 16:07:46 [11614]:   File "/usr/local/lib/python2.7/dist-packages/fishnet.py", line 657, in run_inner
Jun 27 16:07:46 [11614]:     timeout=HTTP_TIMEOUT)
Jun 27 16:07:46 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 107, in post
Jun 27 16:07:46 [11614]:     return request('post', url, data=data, json=json, **kwargs)
Jun 27 16:07:46 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 53, in request
Jun 27 16:07:46 [11614]:     return session.request(method=method, url=url, **kwargs)
Jun 27 16:07:46 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
Jun 27 16:07:46 [11614]:     resp = self.send(prep, **send_kwargs)
Jun 27 16:07:46 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
Jun 27 16:07:46 [11614]:     r = adapter.send(request, **kwargs)
Jun 27 16:07:46 [11614]:   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 426, in send
Jun 27 16:07:46 [11614]:     raise ConnectionError(err, request=request)
Jun 27 16:07:46 [11614]: ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
Jun 27 16:07:54 [11614]: ><> 2: DEBUG: "POST /fishnet/acquire HTTP/1.1" 502 1733
Jun 27 16:07:54 [11614]: ><> 2: ERROR: Server error: HTTP 502 Bad Gateway. Backing off 15.0s
Jun 27 16:07:57 [11614]: ><> 1: Started Stockfish 2018-05-05 64 POPCNT Multi-Variant, threads: ++++ (4), pid: 27754

```

**Comment by niklasf** [comment]
Hang on, were currently debugging connection issues after switching to a new server.

**Comment by lazydroid** [comment]
ok. now it's more or less normal, thanks! =)
