### ISSUE TITLE
"AttributeError: 'module' object has no attribute 'main'" on mac 

### ISSUE THREAD

**Issue by jayanthdeejay** [niklasf/fishnet#91]
I've been running fishnet on my macbook and have been encountering the following error recently. Any ideas?

```shell
stockfish % python -m fishnet --auto-update
.   _________         .    .
.  (..       \_    ,  |\  /|
.   \       O  \  /|  \ \/ /
.    \______    \/ |   \  /      _____ _     _     _   _      _
.       vvvv\    \ |   /  |     |  ___(_)___| |__ | \ | | ___| |_
.       \^^^^  ==   \_/   |     | |_  | / __| '_ \|  \| |/ _ \ __|
.        `\_   ===    \.  |     |  _| | \__ \ | | | |\  |  __/ |_
.        / /\_   \ /      |     |_|   |_|___/_| |_|_| \_|\___|\__| 1.15.9
.        |/   \_  \|      /
.               \________/      Distributed Stockfish analysis for lichess.org


### Updating ...

Waiting 11.2s before update ...

$ pip install --user --upgrade https://files.pythonhosted.org/packages/16/ba/f0af5b28817cd8797aa86d3637a89b3de108d8b70c185cedc31fe69a793d/fishnet-1.15.10.tar.gz
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/dungavjk/Library/Python/2.7/lib/python/site-packages/fishnet.py", line 1916, in <module>
    sys.exit(main(sys.argv))
  File "/Users/dungavjk/Library/Python/2.7/lib/python/site-packages/fishnet.py", line 1900, in main
    sys.exit(commands[args.command](args))
  File "/Users/dungavjk/Library/Python/2.7/lib/python/site-packages/fishnet.py", line 1482, in cmd_run
    update_self()
  File "/Users/dungavjk/Library/Python/2.7/lib/python/site-packages/fishnet.py", line 1076, in update_self
    ret = pip.main(["install", "--user", "--upgrade", url])
AttributeError: 'module' object has no attribute 'main'
stockfish %
```

**Comment by jayanthdeejay** [comment]
Thanks! 👍

**Comment by niklasf** [comment]
Thanks for reporting. There's a change in pip 10 that breaks fishnet's --auto-update. I fixed it, but one manual upgrade is required to get that fix.

```
pip install --upgrade --user fishnet
```

**Comment by jayanthdeejay** [comment]
Also, just so you know, sometimes this happens. I can open a new issue if you think this is one! Once again, thank you. 


```shell
><> 1: ENGINE: 58842 >> bestmove c3b5 ponder b8a6
><> 1: ENGINE: 58842 << isready
><> 1: ENGINE: 58842 >> readyok
><> 1: DEBUG: No job found. Backing off 0.8s
><> 1: DEBUG: No job found. Backing off 1.7s
><> 1: DEBUG: No job found. Backing off 1.6s
><> 1: ERROR: Backing off 3.2s after exception in worker
Traceback (most recent call last):
  File "/Users/Library/Python/2.7/lib/python/site-packages/fishnet.py", line 652, in run_inner
    timeout=HTTP_TIMEOUT)
  File "/Users/Library/Python/2.7/lib/python/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/Library/Python/2.7/lib/python/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Library/Python/2.7/lib/python/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))
><> 1: Started Stockfish 2018-05-05 64 Multi-Variant, threads: ++++ (4), pid: 58851
[fishnet v1.15.11] Analyzed 59 positions, crunched 207 million nodes
[fishnet v1.15.11] Analyzed 59 positions, crunched 207 million nodes
```

**Comment by niklasf** [comment]
If this happens only (somewhat) rarely then it shouldn't be a big deal. Site updates, our server migration on Wednesday, temporary connection issues would all cause similar issues and fishnet should just keep working.

**Comment by lxiao168** [comment]
Any progress?  

Same problem as below:
  exec code in run_globals
  File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1944, in <module>
    sys.exit(main(sys.argv))
  File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1928, in main
    sys.exit(commands[args.command](args))
  File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1514, in cmd_run
    stockfish_command = get_stockfish_command(conf)
  File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1453, in get_stockfish_command
    return validate_stockfish_command(os.path.join(".", filename), conf)
  File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 1302, in validate_stockfish_command
    _, variants = uci(process)
  File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 384, in uci
    command, arg = recv_uci(p)
  File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 370, in recv_uci
    command_and_args = recv(p).split(None, 1)
  File "/root/.local/lib/python2.7/site-packages/fishnet.py", line 359, in recv
    raise EOFError()
EOFError

**Comment by niklasf** [comment]
This looks like a completely unrelated/new problem. Please make a new issue with more details about your OS and the complete output.
