### ISSUE TITLE
stockfish segfaults when trying to analyze this horde position on Arch x64 with an AMD CPU

### ISSUE THREAD

**Issue by lakinwecker** [niklasf/fishnet#93]
```
wget https://github.com/niklasf/Stockfish/releases/download/fishnet-250718/stockfish-x86_64-modern
chmod +x stockfish-x86_64-modern
./stockfish-x86_64-modern
```

```
setoption name Threads value 24
setoption name Hash value 2048
setoption name UCI_Variant value Horde
position fen r7/p3kP2/4P3/3P3r/PPP4P/P2nq1P1/PP5P/1P6 b - - 0 42
```

```
Thread 1 "stockfish-x86_6" received signal SIGSEGV, Segmentation fault.
0x000000000042512e in Position::set_check_info(StateInfo*) const ()
(gdb) where
#0  0x000000000042512e in Position::set_check_info(StateInfo*) const ()
#1  0x0000000000425bc4 in Position::set(std::string const&, bool, Variant, StateInfo*, Thread*) ()
#2  0x000000000044db65 in (anonymous namespace)::position(Position&, std::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >&, std::unique_ptr<std::deque<StateInfo, std::allocator<StateInfo> >, std::default_delete<std::deque<StateInfo, std::allocator<StateInfo> > > >&) [clone .48502] ()
#3  0x000000000044a3af in UCI::loop(int, char**) ()
#4  0x000000000041ffa3 in main ()
```

**Comment by ddugovic** [comment]
Please try this input:

```
setoption name Threads value 24
setoption name Hash value 2048
setoption name UCI_Variant value horde
position fen r7/p3kP2/4P3/3P3r/PPP4P/P2nq1P1/PP5P/1P6 b - - 0 42
```

**Comment by lakinwecker** [comment]
Yes, that seems to fix it. Sorry for the noise.
